searchapp/urls.py
from django.conf.urls import patterns, url

from searchapp import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<note_id>\d+)/$', views.detail, name='detail'),
)

searchproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'searchproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$',include('searchapp.urls',namespace="searchapp")),
    (r'^search/', include('haystack.urls')),
    url(r'^create/$', 'searchapp.views.create_note', name='create'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^__alohaeditor__/', include('aloha_editor.urls', namespace='aloha_editor')),
)

searchapp/models.py
from django.db import models

# Create your models here.


class Note(models.Model):
    title = models.CharField(max_length=1000, unique=True)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

searchapp/forms.py
from django import forms
from searchapp.models import Note

class CreateNotesForm(forms.Form):
    title = forms.CharField(label='Title',max_length=1000,widget=forms.TextInput(attrs={'class':'form-control','placeholder': 'Please enter Usefull Note Title here'}))
    body = forms.CharField(label='body',widget=forms.Textarea(attrs={'class':'form-control','placeholder': 'Please enter usefull description about the note'}))

    def clean(self):
        cleaned_data = super(CreateNotesForm, self).clean()
        title = cleaned_data.get("title")
        body = cleaned_data.get("body")
        if Note.objects.filter(title=title):
            raise forms.ValidationError('This Title is already in use. Please supply a different Title.')

searchapp/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from searchapp.models import Note
from searchapp.forms import CreateNotesForm

from django.utils.safestring import mark_safe

from django.contrib import messages

# Create your views here.
def index(request):
    latest_notes_list = Note.objects.all().order_by('-timestamp')
    paginator = Paginator(latest_notes_list, 5) # Show 5 notes per page
    page = request.GET.get('page')
    try:
        notes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        notes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        notes = paginator.page(paginator.num_pages)
    template = loader.get_template('searchapp/index.html')
    context = RequestContext(request, {'latest_notes_list': notes, })
    return HttpResponse(template.render(context))

def detail(request,note_id):
    try:
        note = Note.objects.get(pk=note_id)
    except Note.DoesNotExist:
        raise Http404
    return render_to_response('note_detail.html', {'note': note})

def create_note(request):
    if request.method == "GET":
        form = CreateNotesForm()
    else:
        form = CreateNotesForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            body = form.cleaned_data['body']
            note = Note.objects.create(title=title,body=body)
            note.save()
            messages.success(request, 'Notes saved sucessfully')
            return redirect('/')
        return  render(request,'searchapp/create_note.html',{'form': form},context_instance=RequestContext(request))
    form = CreateNotesForm()
    return  render(request,'searchapp/create_note.html',{'form': form},context_instance=RequestContext(request))

searchapp/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
  <head>
    <title>{% block title %}This is my new project home page{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <style type="text/css">
    li {
      list-style: none;
    }
    .center{
      text-align: center;
    }
    ::-webkit-input-placeholder {
   text-align: center;
}

:-moz-placeholder { /* Firefox 18- */
   text-align: center;  
}

::-moz-placeholder {  /* Firefox 19+ */
   text-align: center;  
}

:-ms-input-placeholder {  
   text-align: center; 
}


    </style>
  </head>
  <body style="padding-top:60px">
        <div class="container">
          <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
              <a class="navbar-brand" href="/">Haystack Project</a>
              <a class="navbar-brand" href="/">All Notes</a>
              <a class="navbar-brand" href="/create/">Create Notes</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
              </ul>
            </div>
          </div>
        {% block content %}
        {% endblock content %}
        </div>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  </body>
</html>

searchapp/templates/search/search.html
{% extends 'base.html' %}
{% block content %}
<h2>Search</h2>
<form method="get" action=".">
<table>
{{ form.as_table }}
<tr>
<td>&nbsp;</td>
<td>
<input type="submit" value="Search">
<a href="/"><button type="button">Go Back</button></a>
</td>
</tr>
</table>
{% if query %}
<h3>Results</h3>
{% for result in page.object_list %}
<ul class="list-group">
<li class="list-group-item">

            <h1>{{ result.object.title }}</h1>
            <p>{{ result.object.body }}</p>
</li>
</ul>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if page.has_previous or page.has_next %}
<div>
{% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_
|
{% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }
</div>
{% endif %}
{% else %}
{# Show some example queries to run, maybe query syntax, something else? #}
{% endif %}
{% endif %}
{% endif %}
</form>
{% endblock %}

searchapp/templates/searchapp/create_note.html
{% extends "base.html" %}
{% block content %}
<form action=''  method='post'>
        {% csrf_token %}
        <fieldset>
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
        </div>
        {% endif %}
            {% for field in form %}
            <p >{{ field.label_tag }} {{ field }}</p>
            {% if field.errors %}
            <div class="alert alert-danger" role="alert">
            {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </fieldset>
        <input  type="submit" class="btn btn-info form-control" value='Create Notes' id="create_note">
</form>
{% endblock %}

searchapp/templates/searchapp/index.html
{% extends 'base.html' %}
{% block content %}
{% if latest_notes_list %}
{% load humanize %}
    <ul>
    {% if messages %}
<ul class="messages list-group" >
    {% for message in messages %}
    <li class="list-group-item alert alert-success " {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <form id="search" action='/search/'>
                            <h3 class="center">Search Any Notes Here:</h3><input class="small input-text form-control" placeholder="Enter search text" name="q" type="search">
                            <br/>
                            <input class="form-control btn btn-info" value="GO" type="submit">
                        </form>
                        <br/><br/>
    {% for note in latest_notes_list %}
        <ul class="list-group">
        <li class="list-group-item">
            <h1><a href="{% url 'searchapp:detail' note.id %}">{{ note.title }}</a></h1>
            <p>Posted {{ note.timestamp|naturaltime }} </p>
            <p>{{note.id|ordinal }}-post</p>
            <p>{{ note.body }}</p>
        </li>
        </ul>
    {% endfor %}
    <div class="pagination">
    <span class="step-links">
        {% if latest_notes_list.has_previous %}
            <a href="?page={{ latest_notes_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ latest_notes_list.number }} of {{ latest_notes_list.paginator.num_pages }}.
        </span>

        {% if latest_notes_list.has_next %}
            <a href="?page={{ latest_notes_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    </ul>
{% else %}
    <p>No notes are available.</p>
{% endif %}
{% endblock %}

searchapp/templates/searchapp/note_detail.html
{% load aloha_editor %}
{% extends 'base.html' %}
  {% if user.is_authenticated %}
    {% include "aloha_editor/css.html" %}
    {% include "aloha_editor/js.html" %}
  {% endif %}
  <h1>{{ note.title }}</h1>
  {% aloha_editor note.body %}